infection/site

- src/guide/command-line-options.md
The finder component allows for filtering on directories as well, but we didn't have it documented this was possible for infection.
> Add documentation for directory filter

- src/guide/command-line-options.md
Hi, :wave: 
Here's my attempt to fix #41.
By inserting the word "both" in the sentence it should be more clear that both report types are required. I realize the issue described something about underlining the word "both".
If you still require this, please let me know.
> Use the word "both" in the PHPUnit --coverage docs

- src/guide/mutators.md
> Fix: Use plural

- src/guide/mutators.md
- src/guide/profiles.md
This PR
[x] adds documentation for the newly added `UnwrapStrToUpper` mutator
See infection/infection#535.
> Added documentation for UnwrapStrToUpper mutator

- src/guide/mutators.md
Documentation for https://github.com/infection/infection/pull/599
> Add documentation for TrueValue mutator setting

- src/guide/mutators.md
> Fix: Use consistent naming for parameters

- src/guide/mutators.md
> Fix: Remove duplicate

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See: https://github.com/infection/infection/pull/643
> Enhancement: Implement UnwrapLcFirst mutator

- src/guide/mutators.md
- src/guide/profiles.md
Also added missed mutators to the `@operator` profile
Doc for https://github.com/infection/infection/pull/641
> Documentation for Null Assignment Coalesce mutator

- src/guide/mutators.md
- src/guide/profiles.md
Relates to PR https://github.com/infection/infection/pull/649
Addresses issue: https://github.com/infection/infection/issues/597
> #597 ArrayItemRemoval doc

- src/guide/mutators.md
- src/guide/profiles.md
Relates to new mutator https://github.com/infection/infection/issues/654 (PR https://github.com/infection/infection/pull/664)
> #654 mbstring mutator doc

- src/guide/command-line-options.md
> Fix unexisting log verbosity debug option

- src/guide/profiles.md
Method in doc doesn't match the method in config example.
> Typo in ignored methods

- src/guide/installation.md
It's hard to see which infection version can be used with which PHP version, so I created a table based on the information in the release notes and in `composer.json`.
**PHP version 7.2 / infection >= 0.14**
* https://github.com/infection/infection/blob/0.14.0/composer.json#L45
* https://infection.github.io/2019/09/20/whats-new-in-0.14.0/
**PHP version 7.1 / infection >= 0.10**
* https://github.com/infection/infection/blob/0.10.0/composer.json#L60
* https://infection.github.io/2018/08/11/whats-new-in-0.10.0/
**PHP version 7.0 / infection < 0.10**
* https://github.com/infection/infection/blob/0.1.0/composer.json#L28
> added php compatibility matrix

- src/guide/command-line-options.md
The filename requirements for junit coverage were recently changed from phpunit.junit.xml to junit.xml. The docs do specify the correct name however the example still uses the old name.
> Update coverage example to output junit.xml

- src/guide/index.md
The % in the example doesn't match the ones from the report, this PR fixes that.
> [DOCS] Adjusting the % to match explanaition.

- src/guide/mutators.md
- The documentation was referring to the `ConcatOperandRemoval` mutator as `ConcatOperatorRemoval`
> Fix incorrect mutator name: ConcatOperandRemoval

- src/guide/index.md
In the documentation the recommended version for PHP was set to 7.1 and above, but in `composer.json` the requirement was already set to PHP 7.4 or 8.0. It's a small change, but at least it keeps the documentation in sync with the package requirements.
> Update: PHP version mismatch composer requirement

- src/guide/command-line-options.md
- src/guide/github-sponsors.md
- src/guide/index.md
- src/guide/installation.md
- src/guide/supported-test-frameworks.md
- src/guide/usage.md
For https://github.com/infection/infection/pull/1516
> Document `Pest` test framework support

- src/guide/mutators.md
- src/guide/profiles.md
Related to: https://github.com/infection/infection/pull/1529
> Add Docs for New Spread Mutators

- src/guide/mutation-badge.md
- src/guide/usage.md
Replaced `logs.badge.branch` with `logs.badge.matchBranchRegex` in examples,
since it is much more powerful, and probably a better long-term solution
to more complex scenarios.
This patch complements https://github.com/infection/infection/pull/1538
> Documented `logs.badge.branch` accepting a regular expression

- src/guide/usage.md
As we talked in the #infection channel of symfony-devs Slack, the documentation for the `excludes` key of the configuration file could have more examples to show its usage. Besides, as the glob pattern does not work equally in all OS, we talked that it is better to use regular expressions rather than the glob pattern, and that the documentation could show that.
This PR tries to add that information to the documentation.
Please, let me know if I can add anything else.
Thank you!
> Add some examples to "excludes" key of configuration settings

- src/guide/usage.md
This is just a small fix in the usage guide: when I added some example cases, I forgot the complete path in one of the examples, that may misguide the users.
Thank you!
> Small fix in usage guide

- src/guide/command-line-options.md
Docs for https://github.com/infection/infection/pull/1632
> Add docs for `--git-diff-lines` option

- src/guide/command-line-options.md
- src/guide/usage.md
Docs for https://github.com/infection/infection/pull/1625
> Add information about HTML logger usage with generated example

- src/guide/command-line-options.md
- src/guide/mutation-badge.md
- src/guide/usage.md
docs for https://github.com/infection/infection/pull/1629
> Add docs for `stryker` logger (mutation badge, cloud HTML report)

- src/guide/command-line-options.md
- src/guide/usage.md
For https://github.com/infection/infection/pull/1645
> The Github Actions logger is now automatically detected

- src/guide/installation.md
Following the instructions, I installed v0.26.13 on a PHP 7.4 project. I then ran into an incompatibility issue. 
The last compatible version for PHP 7.4 is 0.26.6, so I suggest it is reflected in the installation instructions for clarity.
> Clarifying installation version number for PHP 7.4

- src/guide/index.md
This PR fixes a broken link. The `Mutation Testing Repository` is no longer accessible, and I could not find it on `https://www.ucl.ac.uk/computer-science/ucl-computer-science` (which appears to be the website that replaces `http://crestweb.cs.ucl.ac.uk/`). Fortunately, the original link was archived.
> Mutation Testing Repository: fix broken link

- themes/infection/layout/index.ejs
- themes/infection/layout/partials/main_menu.ejs
Tools like PHPStan or Psalm have easy-accessible playgrounds, while Infection has it described somewhere deep in the docs, which I personally find unnecessary. It's much better to have it directly on the landing page and always in top menu.
> Easy-accessible Playground URL

- src/guide/how-to.md
fixed: `Read more about --git-diff-lines` on https://infection.github.io/guide/how-to.html#By-using-git-diff-lines-option
I didn't see the same mistake anywhere else
https://github.com/search?q=repo%3Ainfection%2Fsite+%22%5D%28%28%22&type=code
> fix(how-to.md): broken link at how-to/By-using-git-diff-lines-option

- themes/infection/layout/layout.ejs
- themes/infection/layout/partials/main_menu.ejs
- themes/infection/source/css/_common.styl
- themes/infection/source/css/_dark-theme.styl
- themes/infection/source/js/theme-switch.js
Follow up for https://github.com/infection/playground/pull/11
Add support for dark them by AI (JetBrains Junie)
This code is in 99% written by UI (JetBrainsJunie) which is a nice experiment when Junie is released.
While the code quality is not perfect, I'm ok here as I explicitly didn't want to use any JS frameworks here. As simple as that and it does the work!
Light theme:
Dark theme:
> Support dark theme

- src/guide/installation.md
I was having some skill issues understanding installation requirements. Maybe this clarifies a little bit about using older PHP versions.
> docs: clariy usage of Infection for older PHP versions
