infection/site

- src/guide/command-line-options.md
- src/guide/compare.md
- src/guide/index.md
- src/guide/using-with-ci.md
This doc PR is for https://github.com/infection/infection/pull/16
> Add documentation about ci threshold options

- src/guide/command-line-options.md
Added option '-c|--configuration' for custom configuration file path. See: https://github.com/infection/infection/pull/28
> Added option '-c|--configuration' for custom configuration file path.

- src/guide/index.md
- src/guide/installation.md
Documentation PR for https://github.com/infection/infection/pull/37
> Update documentation to mention phpdbg

- src/guide/installation.md
Add notes on installing Infection through Homebrew
> Add installation notes for Homebrew

- src/guide/command-line-options.md
See https://github.com/infection/infection/pull/84
> Add comma separated files filter

- src/guide/usage.md
Also see https://github.com/infection/infection/pull/117
> Warn users about excluding test files

- src/guide/usage.md
https://github.com/infection/infection/pull/120
> Add `excludes` option and mark `exlude` as deprecated

- src/guide/usage.md
https://github.com/infection/infection/pull/140
> Add `tempDir` description

- src/guide/usage.md
See: https://github.com/infection/infection/pull/135#discussion_r164550446
> Add new file loggers

- src/guide/usage.md
Remove old `exclude` option. (https://github.com/infection/infection/issues/121)
> Remove `exclude` option

- src/guide/command-line-options.md
Documentation for https://github.com/infection/infection/pull/176/files
> Documentation for existing coverage option

- src/guide/command-line-options.md
https://github.com/infection/infection/pull/185
> Add information about --initial-tests-php-options

- src/guide/command-line-options.md
Documentation for https://github.com/infection/infection/pull/198
> Add ignore-msi-with-no-mutations

- src/guide/compare.md
- src/guide/mutation-badge.md
- src/guide/using-with-ci.md
- themes/infection/layout/partials/toc.ejs
Documentation for https://github.com/infection/infection/pull/207
> Add mutation badge documentation

- src/guide/command-line-options.md
- src/guide/profiles.md
- src/guide/usage.md
- src/guide/using-with-ci.md
Please don't merge until we are sure on the names of profiles.
> Add documentation for profiles and ignore options

- src/guide/usage.md
Adding Documentation For New Config File Options
> Adding Docs For New Config Params

- src/guide/usage.md
Documentation for https://github.com/infection/infection/pull/323
> Add info about how to use custom autoloader/bootstrap file

- src/guide/command-line-options.md
This PR covers https://github.com/infection/infection/pull/357
> Add --debug option

- src/guide/mutators.md
Added by https://github.com/infection/infection/pull/389
> Document Coalesce mutator

- src/guide/command-line-options.md
- src/guide/index.md
- src/guide/installation.md
- src/guide/mutation-badge.md
- src/guide/usage.md
For https://github.com/infection/infection/issues/392
> Add info about how to use with Xdebug

- src/guide/index.md
- src/guide/installation.md
See https://github.com/infection/infection/pull/415
> Update documentation to require php 7.1

- src/guide/mutators.md
- src/guide/profiles.md
See https://github.com/infection/infection/pull/383
> Update documentation with PregMatchMatches mutator

- src/guide/installation.md
- src/guide/usage.md
- src/guide/using-with-ci.md
For https://github.com/infection/infection/pull/436
> Replace OpenSSL with GPG signing

- src/guide/command-line-options.md
- src/guide/profiles.md
- src/guide/usage.md
See https://github.com/infection/infection/pull/454
> Rename infection-log.txt -> infection.log

- src/guide/command-line-options.md
For pull request: infection/infection#481
Also fixed a typo.
> Explain addition of --testsuite exclusion from test-framework-options

- themes/infection/layout/layout.ejs
I hope the missing ms-tile is okay? 
The icon generator that I used didn't support that it seems.
> Adjust icons in layout.ejs

- src/guide/index.md
Hi, thanks for this!
Was reading through the docs and noticed what seems like a typo (suit -> suite). Here is a quick pr fixing that.
Thanks again. Keep up the good work!
> Fix typo in getting started

- src/guide/mutators.md
- src/guide/profiles.md
For https://github.com/infection/infection/pull/391
> Add documentation to reflect identical and equal mutators

- src/guide/mutators.md
Missing docs for https://github.com/infection/infection/pull/513.
Fixes #70
> Add docs for Unwrap mutators

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/527.
> Enhancement: Implement UnwrapArrayReverse mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/529.
> Enhancement: Implement UnwrapArrayFlip mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/539.
> Enhancement: Implement UnwrapStrRepeat mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/536.
> Enhancement: Implement UnwrapArrayReplace mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/534.
> Enhancement: Implement UnwrapStrToLower mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/545.
> Enhancement: Implement UnwrapArrayReplaceRecursive mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/550.
> Enhancement: Implement UnwrapArrayCombine mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/555.
> Enhancement: Implement UnwrapArrayKeys mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/554.
> Enhancement: Implement UnwrapArrayValues mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/556.
> Enhancement: Implement UnwrapArrayUnique mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/583.
> Enhancement: Implement UnwrapArrayDiffUkey mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/584.
> Enhancement: Implement UnwrapArrayIntersectKey mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayIntersectUassoc mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/590.
> Enhancement: Implement UnwrapArrayColumn mutator

- src/guide/usage.md
Debug log is an internal one... check https://github.com/infection/infection/pull/569
> Remove debug log

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/593.
> Enhancement: Implement UnwrapArrayIntersectUkey mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/594.
> Enhancement: Implement UnwrapArrayMergeRecursive mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
💁‍♂️ See https://github.com/infection/infection/pull/605.
> Enhancement: Implement UnwrapArraySplice mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR
💁‍♂️ See https://github.com/infection/infection/pull/614.
> Enhancement: Implement UnwrapArrayUdiffAssoc mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayUdiffUassoc mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayUdiff mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayUintersectAssoc mutator

- src/guide/mutators.md
- src/guide/profiles.md
Documentation for new mutator https://github.com/infection/infection/pull/635
> Mutator: UnwrapUcFirst

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapTrim mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayUintersectUassoc mutator

- src/guide/mutators.md
- src/guide/profiles.md
> Enhancement: Implement UnwrapArrayUintersect mutator

- src/guide/mutators.md
- src/guide/profiles.md
This PR:
Relates: https://github.com/infection/infection/issues/644
Relates: https://github.com/infection/infection/issues/514
> Issue #644: Add documentation related to the new unwrap mutator ucwords.

- src/guide/profiles.md
Docs MR For https://github.com/infection/infection/pull/663
> Adding Docs For Line Numbers In Mutators Ignore

- src/guide/installation.md
- src/guide/usage.md
See: https://github.com/infection/infection/pull/688
> Remove self update information

- themes/infection/layout/partials/main_menu.ejs
Hey there! First of all, thanks for this testing framework! Mutation testing looks really cool!
Just a quick PR to fix the capitalization of GitHub.
> Fix capitalization of GitHub

- src/guide/mutators.md
For https://github.com/infection/infection/pull/787
> mb_str_split mutator docs

- src/guide/mutators.md
- src/guide/profiles.md
For https://github.com/infection/infection/pull/784
> Mutator: Spread operator in Array Expression - docs

- src/guide/usage.md
https://github.com/infection/infection/pull/821 adds support for writing the log contents to the terminal, this PR documents it
> Add a line about the new feature for writing logs to streams

- src/guide/mutators.md
- src/guide/profiles.md
This PR
See https://github.com/infection/infection/pull/831
> Implement UnwrapStrReplace mutator

- src/guide/command-line-options.md
> Fixed typo

- src/guide/mutators.md
Add information about new **Clone** removal mutator
> Add new clone removal mutator

- src/guide/command-line-options.md
- src/guide/index.md
Related to https://github.com/infection/infection/pull/800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/infection/site/136)
> Add Codeception support notes

- src/guide/installation.md
Just complete the installation page to add pcov as a possible solution for using Infection.
> docs(installation.md): Add pcov as requirement

- src/guide/command-line-options.md
Doc update for https://github.com/infection/infection/pull/941
> Exclude --configuration from PhpUnit options

- src/guide/usage.md
This PR
Related to https://github.com/infection/infection/pull/789.
> Enhancement: Mention options that can be configured via infection.json

- src/guide/command-line-options.md
Doc update for https://github.com/infection/infection/pull/1042
> New option to skip the initial test suite

- src/guide/profiles.md
See https://github.com/infection/infection/pull/1104
> Document the global ignore feature

- src/guide/mutation-badge.md
This PR
Related to https://github.com/infection/infection/pull/1135.
> Enhancement: Update mutation badge documentation

- package.json
- src/guide/command-line-options.md
- src/guide/installation.md
Docs for https://github.com/infection/infection/pull/1141
> Add information about test frameworks adapters

- src/_posts/whats-new-in-0.16.0.md
- src/guide/command-line-options.md
- src/guide/installation.md
- src/guide/using-with-ci.md
I've already created a `016.` branch in `infection/site`, and will create the same for `infection/infection` soon.
As we already discussed, I need some help with this post to explain what performance improvements we did (and everything else that I missed)
> Blog post for 0.16.0

- src/guide/mutators.md
As per https://github.com/infection/infection/pull/1232
> InstanceOf_ mutator

- src/guide/caveats.md
Reference: https://github.com/infection/infection/pull/1240
> Report mutations must occur with CC already started

- src/guide/usage.md
Related to https://github.com/infection/infection/pull/1278
> Add information about `json` logger

- src/guide/usage.md
Depends on infection/infection#1171
> Update usage.md to mention skipped mutations

- README.md
This PR makes the URL to the website in the README.md file clickable.
> Make the URL to the website clickable

- src/guide/profiles.md
This PR fixes broken URLs to mutators in the Profiles page.
> Fix broken URLs in the Profiles page

- src/guide/usage.md
Rel: https://github.com/infection/infection/pull/1313
> Update timeout description

- src/guide/mutators.md
Documentation for https://github.com/infection/infection/pull/1306
> Add description for SharedCaseRemoval mutator

- src/guide/how-to.md
- src/guide/profiles.md
- src/guide/usage.md
Docs for https://github.com/infection/infection/pull/1326
> Document how to ignore mutations matching the source code by regular expression

- src/_posts/whats-new-in-0.18.0.md
Should this be ported to the version branch?
> Add a note on PHPUnit 9.3

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1342
> Update mutators.md with YieldValue mutator

- src/guide/installation.md
Docs for https://github.com/infection/infection/pull/1340
> Drop PHP 7.3 support for Infection

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1389
> Update mutators.md with FlipCoalesce mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1390
> Update mutators.md with Ternary mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1391
> Remove old Coalesce mutator and rename FlipCoalesce to Coalesce

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1405
> Update mutators.md with While mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1411
> Update mutators.md with DoWhile mutator

- src/guide/mutators.md
ref: https://github.com/infection/infection/pull/1443
> Remove OneZeroInteger mutator

- src/guide/mutators.md
> Add ConcatOperatorRemoval to mutators.md

- src/guide/mutators.md
> Add Concat to mutators.md

- src/guide/mutators.md
ref: https://github.com/infection/infection/pull/1457
> Update mutators.md with new NullSafe mutators

- src/guide/mutators.md
- src/guide/profiles.md
related to https://github.com/infection/infection/pull/1455
> Add docs for new regex mutators

- src/guide/mutators.md
- src/guide/profiles.md
related to https://github.com/infection/infection/pull/1462
> Add docs for new regex mutator - PregMatchRemoveFlags

- src/guide/command-line-options.md
- src/guide/debugging-issues.md
- src/guide/infection-playground.md
- themes/infection/layout/partials/toc.ejs
Add an article about how to debug potential issues with this option
Related to https://github.com/infection/infection/pull/1465
> Add docs for `--noop` option. 

- src/guide/how-to.md
- src/guide/usage.md
Docs for https://github.com/infection/infection/pull/1504
> Add documentation for `INFECTION` and `TEST_TOKEN` environment variables

- src/guide/installation.md
> Update path to composer

- src/guide/command-line-options.md
Documents change proposed in https://github.com/infection/infection/pull/1654
> Document use of three dot diff

- src/guide/command-line-options.md
For https://github.com/infection/infection/pull/1723
> Add information about new `--threads=max` value to automatically detect the number of CPU cores

- src/guide/command-line-options.md
- src/guide/compare.md
- src/guide/debugging-issues.md
- src/guide/how-to.md
- src/guide/mutation-badge.md
- src/guide/mutators.md
- src/guide/usage.md
Add some words about support of `json` and `json5`
Docs for https://github.com/infection/infection/pull/1727
> Change the format of config file to `json5`

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1740
> Update mutators.md with UnwrapFinally mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1741
> Update mutators.md with Catch_ mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1742
> Update mutators.md with CatchBlockRemoval mutator

- src/guide/mutators.md
Ref: https://github.com/infection/infection/pull/1744
> Update mutators.md with MatchArmRemoval mutator

- src/guide/installation.md
- src/guide/mutators.md
- src/guide/using-with-ci.md
Related to https://github.com/infection/infection/pull/1753
> Add docs for "if condition negation" mutators

- src/guide/command-line-options.md
- src/guide/usage.md
Documentation for https://github.com/infection/infection/pull/1878
> Document GitLab code quality format logger.

- themes/infection/source/css/index.styl
@maks-rafalko you were faster than my self review 😆. This fixes spaces between buttons on landing page.
> Fix spacing between hero buttons

- src/guide/command-line-options.md
Related to https://github.com/infection/infection/pull/1919
> Document new `--map-source-class-to-test` option

- src/guide/custom-mutators.md
see https://github.com/infection/infection/pull/1969
> Add information about `custom-mutator` CLI generator

- src/guide/mutators.md
- src/guide/profiles.md
Docs for https://github.com/infection/infection/pull/2009
> Add `ArrayAll` mutator

- src/guide/mutators.md
- src/guide/profiles.md
Docs for https://github.com/infection/infection/pull/2010
> Add `ArrayAny` mutator

- src/guide/command-line-options.md
- src/guide/index.md
- src/guide/installation.md
- src/guide/supported-test-frameworks.md
Related to https://github.com/infection/infection/pull/2047
> Remove Pest test framework from the docs

- src/guide/mutators.md
- src/guide/profiles.md
Docs for https://github.com/infection/infection/pull/2050
> Add `ArrayFindKey` mutator

- src/guide/mutators.md
- src/guide/profiles.md
Docs for https://github.com/infection/infection/pull/2049
> Add `ArrayFind` mutator

- src/guide/usage.md
Docs for https://github.com/infection/infection/pull/2158
> Add docs for `threads` configuration key (pair for `--threads`)

- src/guide/command-line-options.md
Docs for https://github.com/infection/infection/pull/2226
> Add docs for `--id`

- src/guide/command-line-options.md
counterpart of https://github.com/infection/infection/pull/2216
> Document new `--show-mutations` behaviour

- src/guide/usage.md
Docs for https://github.com/infection/infection/pull/2301
> Add docs for setting `staticAnalysisTool` in a config file

- src/guide/command-line-options.md
counterpart of https://github.com/infection/infection/pull/2336
> Remove `--only-covered`; Introduce `--with-uncovered` instead

- src/guide/command-line-options.md
- src/guide/usage.md
Documentation for https://github.com/infection/infection/pull/2374
> Document `--static-analysis-tool-options`
